name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      ADZUNA_BASE_URL: ${{ secrets.ADZUNA_BASE_URL }}
      # Add any other environment variables you need here
      
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run tests
        run: npm test
        env:
          # Redundant but ensures environment variables are available during test execution
          ADZUNA_BASE_URL: ${{ secrets.ADZUNA_BASE_URL }}